apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdc-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: hdc-api
  template:
    metadata:
      labels:
        app: hdc-api
    spec:
      containers:
        - name: hdc-api
          image: prashantdhepe/hdc-api:latest
          imagePullPolicy: Always
          command: ["php", "artisan", "serve"]
          args: ["--host=0.0.0.0", "--port=8000"]
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: hdc-api-env
            - secretRef:
                name: hdc-api-secret
