apiVersion: v1
kind: ConfigMap
metadata:
  name: hdc-api-env
data:
  APP_NAME: "HDC CMS"
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://hdc.local
  ASSET_URL: http://hdc.local
  SESSION_DOMAIN: "hdc.local"

  DB_CONNECTION: mysql
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_DATABASE: hdc_cms
  DB_USERNAME: root
  DB_PASSWORD: root

  CACHE_DRIVER: file
  SESSION_DRIVER: file
  FILESYSTEM_DISK: public
  FILAMENT_FILESYSTEM_DISK: public
  LIVEWIRE_UPLOAD_DISK: public
