apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hdc-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: hdc.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hdc-frontend-service
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hdc-api-service
                port:
                  number: 80
